services:
  server-app:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3005:3000"
    volumes:
      - ./:/server:ro  
    depends_on:
      - db-mongo
    networks: 
      - my-bridge 
    restart: on-failure   

  db-mongo:
    image: mongo:7.0.3
    volumes: 
      - /home/olena/Documents/fm_backup_mongo:/data/db
    networks: 
      - my-bridge 
    restart: always   

networks:
  my-bridge: 
