POST http://172.17.0.3:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "content": "new task 6",
  "deadLine": "2023-12-13",
  "owner": {
    "name": "Alex",
    "email": "alex@gmail.com",
    "raiting": 3
  }
}